name: BOOK STORE application CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: '3.11'
        environment-file: environment.yml
        activate-environment: book_store

    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name book_store

    - name: Run tests with coverage
      run: |
        conda activate book_store
        pytest --cov --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml
        flags: unittests
        fail_ci_if_error: true
        verbose: true
